### ISSUE TITLE
Need a Help, Pls!

### ISSUE THREAD

**Issue by rgurdov** [reu/omniauth-steam#17]
Hello, Im new in WebDevelopment and especially in Rails. I tried to install without "Devise", only using omniauth. Trying to callback HASH request as like in Railscasts (https://youtu.be/KOnRf1K6Eg8?t=4m42s). How can i do? 

I really wiill be appreciate to help. Thank You!

**Comment by flou** [comment]
I'm guessing you're having troubles with the error `No route matches [POST] ...`
Steam is a bit different, it responds with a POST request so you may need to add a specific route to handle this:
```ruby
post "auth/steam/callback", to: "sessions#create"
```

This post explains it very well: http://grschafer.com/guides/2013/09/07/steam-openid-and-webapi-with-rails/

**Comment by reu** [comment]
Wow, very nice post you link up there @flou!

Anyway, I will close this, as it is not a bug on OmniauthSteam.
