### ISSUE TITLE
why not use steamcommunity profile xml instead of requiring api key?

### ISSUE THREAD

**Issue by Fedcomp** [reu/omniauth-steam#18]
Example with my profile: http://steamcommunity.com/profiles/76561198013853203?xml=1

This would allow to get rid of api key requirement, as whole information is available without a need of api key.

Was there special reasons to use steam api?

**Comment by Fedcomp** [comment]
I tested my idea it and it looks working well, i may provide pull request if you need it.

**Comment by nahtnam** [comment]
:+1: for this. I would really like access to the `customURL` part where it gives you the steam community username.

**Comment by reu** [comment]
This looks good, I was not aware of this API that doesn't require an API key.

**Comment by Fedcomp** [comment]
I'll try provide pull request in week or two.

**Comment by nahtnam** [comment]
@Fedcomp Let me know if you need any help.

**Comment by Fedcomp** [comment]
Allright, it's been awhile. How exactly i should implement pull request for this feature? should it keep api-key support or should we drop it and use only information from xml api?

**Comment by M-Porter** [comment]
This should not be used. The xml API is deprecated and there is no guarantee if/when they will remove it.

**Comment by Fedcomp** [comment]
Oh, i didn't know that, thanks! Can you provide link where it says it's deprecated?

**Comment by M-Porter** [comment]
@Fedcomp here you go https://partner.steamgames.com/documentation/community_data

**Comment by reu** [comment]
Thanks for the info @M-Porter, I will be closing this.
