### ISSUE TITLE
Should redirect to failure path if Steam is not available

### ISSUE THREAD

**Issue by GMMan** [reu/omniauth-steam#19]
Sometimes Steam is in maintenance or otherwise down, and OmniAuth can't access Steam's servers. Rather than causing a server error, it should redirect to the failure page and indicate that Steam is down and to try authenticating later.

**Comment by reu** [comment]
Fully agree! If you wish, you could provide a pull request with the fix and I will gladly merge.

**Comment by vishnukool** [comment]
any update on this ?

**Comment by vishnukool** [comment]
i've provided a pull request please check

**Comment by reu** [comment]
Done =]

**Comment by vishnukool** [comment]
thanks
