### ISSUE TITLE
(steam) Authentication failure! invalid_credentials encountered.

### ISSUE THREAD

**Issue by delpierrem** [reu/omniauth-steam#32]
I guy i have a probleme with my omniauth-steam.
I think the pb is i use auth to have steam id with a registred user, before the fix off claimed url it will work but no i have this problème
Any one can help me ?
Thanks to u

in my terminal 
I, [2018-04-13T11:14:01.392233 #31937]  INFO -- OpenID: WARNING: making https request to https://steamcommunity.com/openid without verifying server certificate; no CA path was specified.
I, [2018-04-13T11:14:01.863875 #31937]  INFO -- OpenID: WARNING: making https request to https://steamcommunity.com/openid/login without verifying server certificate; no CA path was specified.
I, [2018-04-13T11:14:02.285985 #31937]  INFO -- OpenID: Missing required parameter in response from https://steamcommunity.com/openid/login: <http://specs.openid.net/auth/2.0>assoc_type not in this message
I, [2018-04-13T11:14:02.307495 #31937]  INFO -- OpenID: Generated checkid_setup request to https://steamcommunity.com/openid/login using stateless mode.
[...]
[2018-04-13T10:39:06.586316 #28965]  INFO -- OpenID: Error attempting to use stored discovery information: OpenID::TypeURIMismatch
I, [2018-04-13T10:39:06.586447 #28965]  INFO -- OpenID: Attempting discovery to verify endpoint
I, [2018-04-13T10:39:06.586509 #28965]  INFO -- OpenID: Performing discovery on https://steamcommunity.com/openid/id/mon_id 
I, [2018-04-13T10:39:06.587035 #28965]  INFO -- OpenID: WARNING: making https request to https://steamcommunity.com/openid/id/mon_id without verifying server certificate; no CA path was specified.
I, [2018-04-13T10:39:07.087690 #28965]  INFO -- OpenID: Using 'check_authentication' with https://steamcommunity.com/openid/login
I, [2018-04-13T10:39:07.088055 #28965]  INFO -- OpenID: WARNING: making https request to https://steamcommunity.com/openid/login without verifying server certificate; no CA path was specified.
(steam) Authentication failure! invalid_credentials encountered
def failure
    render plain: params.inspect
  end
this show me :
<ActionController::Parameters {} permitted: false>

**Comment by krtschmr** [comment]
gem "omniauth-steam", github: "krtschmr/omniauth-steam"

**Comment by delpierrem** [comment]
Ok i will try this week and give you a feedback :)

**Comment by delpierrem** [comment]
same problem, though I check my API key and it's ok, i dont know why that tells me:
(steam) Authentication failure! invalid_credentials encountered.

**Comment by deniciocode** [comment]
Hello, I have the same error and I do not know why this happens. Has it something todo because of **localhost**? 

I would like to inspect the log for this issue.
