### ISSUE TITLE
Update on rubygems?

### ISSUE THREAD

**Issue by timwis** [reu/omniauth-steam#34]
Hey, I ran into the https error in #30 that was fixed by 5a6cc0d1e739450b18ada224b5731d13ba9977cc. When I switched by Gemfile from

```
gem 'omniauth-steam'
```
to:

```
gem 'omniauth-steam', github: 'reu/omniauth-steam'
```
It fixed the issue. I think you need to increment the version and republish to rubygems, no?

**Comment by Deekor** [comment]
version increment is in #33

**Comment by reu** [comment]
Done
