### ISSUE TITLE
Is this gem still up2date?

### ISSUE THREAD

**Issue by deniciocode** [reu/omniauth-steam#35]
Hey I am trying to use this gem within my rails 6 application and I have some issue. 
Is it possible to have an updated example available for this gem? 

As far as I know by now the usage of devise is not needed when I was to authenticate a user via steam and create a user. 
BUT I have issues to authenticate.

Best Regards

Dennis

**Comment by deniciocode** [comment]
Ok, never mind. After some time dig into omniauth I found all the routes needed to activate the authentication flow.

**Comment by ChalkyBrush** [comment]
I'm getting this in rails 6:

ActionController::RoutingError (No route matches [GET] "/auth/steam"):

how did you resolve this?

**Comment by ChalkyBrush** [comment]
For anyone wondering how to get it working in rails 6:

Omniauth 2.0 requires a POST request for the /auth/{strategy} route,
You will also need the following gem:

gem 'omniauth-rails_csrf_protection', '~> 1.0'
